[[battery.display]]
threshold = 30

[env_var]
variable = "STARSHIP_THIS_PID"
format = "sid [$env_value]($style) "
default = "unknown"

[time]
disabled = false

# 'cc --version' is super slow, so don't.
[c]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[docker_context]
disabled = true
