format='$time$shell$env_var$jobs$battery$git_branch$git_state$line_break$directory$character'

[[battery.display]]
threshold = 50

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[\$](bold green)'
vimcmd_visual_symbol = '[\$](bold yellow)'
vimcmd_replace_symbol = '[\$](bold purple)'
vimcmd_replace_one_symbol = '[\$](bold purple)'

[env_var]
variable = "STARSHIP_THIS_PID"
format = '[$env_value]($style) '
default = "unknown"

[time]
disabled = false
format = '\[[$time]($style)\] '

[shell]
format = "$indicator:"
disabled = false
